### ISSUE TITLE
Possibly incorrect value of the `name` property inside `pyproject.toml` file

### ISSUE THREAD

**Issue by Vladislav0Art** [gitbugactions/gitbug-java#16]
After cloning the repository and running `poetry install` the following is printed:

<img width="1310" alt="Screenshot 2024-02-29 at 20 14 36" src="https://github.com/gitbugactions/gitbug-java/assets/47076189/18c52ec4-e227-487b-ac04-aef9cdcfde0c">

Perhaps, the property `name` should be changed as follows:
```diff
# pyproject.toml:

-name = "gitbug-java"
+name = "gitbug"
```

After the property is changed the command `poetry install` executes with no warning and all the following commands from the instructions are executed normally.

**Comment by andre15silva** [comment]
Hi @Vladislav0Art,

Thanks a lot for your report and interest :)

#17 should fix this, the warning is there because we forgot to disable the package mode for this project.

Nonetheless, you can still use the version under `main` as the warning does not have any further implications for the usage of GitBug-Java.
