### ISSUE TITLE
Inquiry Regarding Test Functionality for gitbug-java

### ISSUE THREAD

**Issue by DaisyPo** [gitbugactions/gitbug-java#25]
Hi,

Thank you for providing this dataset. I was wondering if it includes a test functionality similar to the "defects4j test" in Defects4J, which can be used to validate patches. The datasets seem reproducible, but I haven't been able to find functionality for running triggering tests and relevant tests for patch validation. Looking forward to your reply. Thanks!

**Comment by DaisyPo** [comment]
![a1f34338264d7eaeb5324cce66fc478d](https://github.com/gitbugactions/gitbug-java/assets/56296073/9ba83334-805b-4246-9598-a0c90e2f76ee)
I used this command ` gitbug-java run WORK_DIR` , but the result showed that all tests are missing. Since the glibc version in my OS is older than that needed for the `act` in the directory `bin`. I replaced the `act` with a former version.  I didn't change other configures. Did I do something wrong?

**Comment by Nfsaavedra** [comment]
Hi @DaisyPo!

Sorry for the late reply. As you found out, `gitbug-java run` is the equivalent of `defects4j test` (even though defects4j has some additional functionality for this command that we may add in the future). 

About your problem, we use a modified version of `act` for this project and that's why we provide the binary. It's very likely that the problem you are having is related to that. You can try to compile our version of `act` and see if it works:

1. Clone https://github.com/gitbugactions/act
2. `go build`

If it does not, please tell me what's the version of glibc that you have :)
